export const READ_RECIPE = "READ_RECIPE";
export const DESTROY_RECIPE = "DESTROY_RECIPE";

export const NEW_RECIPE = "NEW_RECIPE";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const UPDATE_RECIPE_FORM_DETAILS = "UPDATE_RECIPE_FORM_DETAILS";

export const FILTER_RECIPES = "FILTER_RECIPES";